"""add Flower

Revision ID: 945b4ec6b88e
Revises: dede295dcabf
Create Date: 2025-04-07 20:40:09.458066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945b4ec6b88e'
down_revision = 'dede295dcabf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flowers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flowers')
    # ### end Alembic commands ###
