"""create items table

Revision ID: 1c1d68815002
Revises: 7eb2fbcb4925
Create Date: 2025-04-12 14:41:03.855594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1d68815002'
down_revision = '7eb2fbcb4925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_status', sa.String(), nullable=True),
    sa.Column('special_requests', sa.String(), nullable=True),
    sa.Column('wristlet_id', sa.Integer(), nullable=True),
    sa.Column('flower_id', sa.Integer(), nullable=False),
    sa.Column('ribbon_id', sa.Integer(), nullable=False),
    sa.Column('accent_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accent_id'], ['accents.id'], name=op.f('fk_items_accent_id_accents')),
    sa.ForeignKeyConstraint(['flower_id'], ['flowers.id'], name=op.f('fk_items_flower_id_flowers')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_items_order_id_orders')),
    sa.ForeignKeyConstraint(['ribbon_id'], ['ribbons.id'], name=op.f('fk_items_ribbon_id_ribbons')),
    sa.ForeignKeyConstraint(['wristlet_id'], ['wristlets.id'], name=op.f('fk_items_wristlet_id_wristlets')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('items')
    # ### end Alembic commands ###
