"""create orders table

Revision ID: 7eb2fbcb4925
Revises: e16902450ba0
Create Date: 2025-04-11 13:00:39.450740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb2fbcb4925'
down_revision = 'e16902450ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('delivery_details', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_orders_event_id_events')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accents', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('flowers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('ribbons', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('wristlets', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wristlets', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('ribbons', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('flowers', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('accents', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('orders')
    # ### end Alembic commands ###
